---
- name: install pakages
  hosts: all
  become: yes

  roles:
    - install


- name: up nexus
  hosts: nexus
  become: yes

  roles:
    - nexus


- name: up jenkins
  hosts: jenkins
  become: yes

  roles:
    - jenkins


- name: install mvn
  hosts: build
  become: yes

  roles:
    - build


- name: install tomcat
  hosts: deploy
  become: yes

  roles:
    - deploy