FROM ubuntu:20.04

#update system
RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install wget -y && \
    apt-get install curl -y && \
    apt-get install dpkg -y &&\
    apt-get install -y gpg

#install java
RUN apt-get update -y && \
    apt-get install default-jdk -y

#install maven
RUN apt-get update -y && \
    apt-get install maven -y

#install docker
RUN apt-get update -y && \
    apt-get install apt-transport-https ca-certificates curl software-properties-common -y && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable" && \
    apt-get update -y && \
    apt-get install docker-ce -y

# Clear cache
RUN apt-get clean -y
