pipeline {
    agent {
        docker {
            image ('dimetrikusk/m3:test1').inside('--privileged')
//             args '--privileged'
        }
    }

    stages {

        stage('Copy project') {
            steps {
                git branch: 'main', credentialsId: 'dimetrikuskGit', url: 'https://github.com/DimetrikusK/boxfuse.git'
            }
        }
        stage('Build project') {
            steps {
                sh 'mvn package'
            }
        }
        stage ('Make docker images'){
            steps{
                sh 'service docker start'
                sh 'docker build -t dimetrikusk/boxfuse:latest .'
            }
        }

        }


    }