pipeline {
    agent {
        docker {
            image 'dimetrikusk/m3:latest'
        }
    }

    stages {

        stage('Copy project') {
            steps {
                git branch: 'main', credentialsId: 'dimetrikuskGit', url: 'https://github.com/DimetrikusK/boxfuse.git'
            }
        }
        stage('Build project') {
            steps {
                sh "java --version"
                sh 'mvn --version'
                sh 'ls -la'
            }
        }
        stage ('Make docker images'){
            steps{
                sh 'cd target &&  docker build -t dimetrikusk/boxfuse:latest .'
            }
        }

        }


    }