---
- name: install jenkins
  hosts: install_jenkins
  become: true

  tasks:
    - name: install java
      apt:
        name: default-jre
        state: present

    - name: download jenkins repo
      apt_key:
        url: 'https://pkg.jenkins.io/debian-stable/jenkins.io.key'
        state: present
      become: true

    - name: ensure to repository is configure
      apt_repository:
        repo:  'deb http://pkg.jenkins.io/debian-stable binary/'
        state: present
    - name: update apt cache
      apt:
        update_cache: yes

    - name: install jenkins
      apt:
        name: jenkins
        state: present

    - name: start jenkins
      service:
        name: jenkins
        enabled: true
        state: started
