---
- name: install jenkins
  hosts: install_jenkins
  become: true

  tasks:

    - name: install java
      apt:
        name: openjdk-11-jre
        state: present

    - name: install jenkins
      apt:
        name: jenkins
        state: present

    - name: start jenkins
      service:
        name: jenkins
        enabled: true
        state: started
