---

- name: start container jenkins
  hosts: jenkins
  become: true

  tasks:
    - name: install jenkins
      docker_container:
        name: jenkins
        image: jenkins/jenkins:lts-jdk11
        user: root
        volumes:
          - /app/jenkins:/var/jenkins_home
        ports:
          - 8080:8080
          - 50000:50000
        restart: true