docker ---
version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
     - '8080:80'
    restart: on-failure:3
#    depends_on: ''

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - '8081:8080'
      - '5000:5000'
    volumes:
      - '/app/jenkins:/app/jenkins'
    restart: on-failure:3

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - '8082:8082'
    volumes:
      - '/app/nexus:/app/nexus'
    restart: on-failure:3

  gitlab:
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'gitlab.example.com'
    environment:
       GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com:8929'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - '8929:8929'
      - '2224:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'

