---
- name: Install JAVA
  apt:
    name: default-jdk
    state: present

- name: Create a Tomcat User
  user:
    name: tomcat

- name: Create a Tomcat Group
  group:
    name: tomcat

- name: Create a Tomcat Directory
  file:
    path: /opt/tomcat9
    owner: tomcat
    group: tomcat
    mode: 755
    recurse: yes

- name: download & unarchive tomcat9
  unarchive:
    src: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.76/bin/apache-tomcat-9.0.76.tar.gz
    dest: /opt/tomcat9
    remote_src: yes

- name: Change ownership of tomcat directory
  file:
    path: /opt/tomcat9
    owner: tomcat
    group: tomcat
    mode: "u+rwx,g+rx,o=rx"
    recurse: yes

- name: Start Tomcat 9 on sever
  shell:
    cmd: ./catalina.sh run &
    chdir: /opt/tomcat9/apache-tomcat-9.0.76/bin
